discovery:
  image: progrium/consul
  expose:
    - "8500"
    - "8400"
    - "53/udp"
  hostname: "node1"
  command: "-server -bootstrap"

registrator:
  image: gliderlabs/registrator
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - "discovery:discovery"
  command: "-internal consul://discovery:8500"

gateway:
  build: gateway-service
  links:
    - "discovery:consul"
  ports:
    - "8080:80"
  environment:
    - "SERVICE_IGNORE=1"



id:
  build: id-service
  links: 
    - "idredis: redis"
  environment:
    - "SERVICE_NAME=id-service"
    - "SERVICE_TAGS=interactive-lecture,private"
  expose:
    - "8080"

idredis:
  image: redis
  environment:
    - "SERVICE_IGNORE=1"


lecture:
  build: lecture-service
  links: 
    - "lectureneo4j: neo4j"
  environment:
    - "SERVICE_NAME=lecture-service"
    - "SERVICE_TAGS=interactive-lecture,public"
  expose:
    - "8080"

lectureneo4j:
  image: tpires/neo4j
  environment:
    - "SERVICE_IGNORE=1"

authentication:
  build: authentication-service
  links:
    - "authpostgres: postgres"
  expose:
    - "8080"
  environment:
    - "SERVICE_NAME=authentication-service"
    - "SERVICE_TAGS=interactive-lecture,public"

authpostgres:
  image: postgres
  environment:
    - "SERVICE_IGNORE=1"


javaevaluation:
  build: java-evaluation-service
  links:
    - "javaevaluationmongo: mongo"
  expose:
    - "8080"
  environment:
    - "SERVICE_NAME=java-evaluation-service"
    - "SERVICE_TAGS=interactive-lecture,public"


javaevaluationmongo:
  image: mongo
  environment:
    - "SERVICE_IGNORE=1"

document:
  build: document-service
  links:
    - "documentmongo: mongo"
  expose:
    - "8080"
  environment:
    - "SERVICE_NAME=document-service"
    - "SERVICE_TAGS=interactive-lecture,public"


documentmongo:
  image: mongo
  environment:
    - "SERVICE_IGNORE=1"



media:
  build: media-service
  links:
    - "mediamongo: mongo"
  expose:
    - "8080"
  environment:
    - "SERVICE_NAME=media-service"
    - "SERVICE_TAGS=interactive-lecture,public"

mediamongo:
  image: mongo
  environment:
    - "SERVICE_IGNORE=1"


acl:
  build: acl-service
  links:
    - "aclpostgres: postgres"
  expose:
    - "8080"
  environment:
    - "SERVICE_NAME=acl-service"
    - "SERVICE_TAGS=interactive-lecture,public"

aclpostgres:
  image: postgresql
  environment:
    - "SERVICE_IGNORE=1"


webuserfrontend:
  build: user-webui-service
  expose:
    - "80"
  environment:
    - "SERVICE_NAME=user-webfrontend-service"
    - "SERVICE_TAGS=interactive-lecture,public"

webadminfrontend:
  build: admin-webui-service
  expose:
    - "80"
  environment:
    - "SERVICE_NAME=admin-webfrontend-service"
    - "SERVICE_TAGS=interactive-lecture,public"

